### PR TITLE
Error patch fixes #3

### LINKED ISSUE #3: Add error pages for irrelevant search terms

### PR DESCRIPTION
**Pull request by ashwini0529**

### CODE REVIEW

**Comment by ashwini0529** [comment]
@daminisatya, is there anything else?

**Comment by daminisatya** [comment]
@ashwini0529 thank you for the quick patch, can you please attach screenshots for the same. 👍

**Comment by ashwini0529** [comment]
@daminisatya , If no results found, it would render : 
screencapture-localhost-5000-visualize-1478340145401
Is there anything else to be added or is this good to go?

**Comment by daminisatya** [comment]
@ashwini0529 great! Thank you 👍

**Pull request merged**
